; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "spider_image_system"
!define PRODUCT_VERSION "1.1.2"
!define PRODUCT_PUBLISHER "zhaoqi.cao"
!define PRODUCT_WEB_SITE "http://caozhaoqi.github.io"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\selenium-manager.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!define MUI_LICENSEPAGE_CHECKBOX
!insertmacro MUI_PAGE_LICENSE "..\..\out\ui_main.dist\SISSoftwareLicence.txt"
; Components page
!insertmacro MUI_PAGE_COMPONENTS
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "spider_image_system"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\ui_main.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\spider_image_system"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR\charset_normalizer"
  SetOverwrite try
  File "..\..\out\ui_main.dist\charset_normalizer\md.pyd"
  File "..\..\out\ui_main.dist\charset_normalizer\md__mypyc.pyd"
  SetOutPath "$INSTDIR\config"
  File "..\..\out\ui_main.dist\config\config.ini"
  File "..\..\out\ui_main.dist\config\user-agent.txt"
  SetOutPath "$INSTDIR\Crypto\Cipher"
  File "..\..\out\ui_main.dist\Crypto\Cipher\_chacha20.pyd"
  File "..\..\out\ui_main.dist\Crypto\Cipher\_raw_aes.pyd"
  File "..\..\out\ui_main.dist\Crypto\Cipher\_raw_aesni.pyd"
  File "..\..\out\ui_main.dist\Crypto\Cipher\_raw_cbc.pyd"
  File "..\..\out\ui_main.dist\Crypto\Cipher\_raw_cfb.pyd"
  File "..\..\out\ui_main.dist\Crypto\Cipher\_raw_ctr.pyd"
  File "..\..\out\ui_main.dist\Crypto\Cipher\_raw_ecb.pyd"
  File "..\..\out\ui_main.dist\Crypto\Cipher\_raw_ocb.pyd"
  File "..\..\out\ui_main.dist\Crypto\Cipher\_raw_ofb.pyd"
  File "..\..\out\ui_main.dist\Crypto\Cipher\_Salsa20.pyd"
  SetOutPath "$INSTDIR\Crypto\Hash"
  File "..\..\out\ui_main.dist\Crypto\Hash\_BLAKE2s.pyd"
  File "..\..\out\ui_main.dist\Crypto\Hash\_ghash_clmul.pyd"
  File "..\..\out\ui_main.dist\Crypto\Hash\_ghash_portable.pyd"
  File "..\..\out\ui_main.dist\Crypto\Hash\_poly1305.pyd"
  File "..\..\out\ui_main.dist\Crypto\Hash\_SHA1.pyd"
  File "..\..\out\ui_main.dist\Crypto\Hash\_SHA256.pyd"
  SetOutPath "$INSTDIR\Crypto\Protocol"
  File "..\..\out\ui_main.dist\Crypto\Protocol\_scrypt.pyd"
  SetOutPath "$INSTDIR\Crypto\Util"
  File "..\..\out\ui_main.dist\Crypto\Util\_cpuid_c.pyd"
  File "..\..\out\ui_main.dist\Crypto\Util\_strxor.pyd"
  SetOutPath "$INSTDIR\cv2"
  File "..\..\out\ui_main.dist\cv2\cv2.pyd"
  SetOutPath "$INSTDIR\data\href_url"
  File "..\..\out\ui_main.dist\data\href_url\klee_result_url.txt"
  SetOutPath "$INSTDIR"
  File "..\..\out\ui_main.dist\libcrypto-1_1.dll"
  File "..\..\out\ui_main.dist\libffi-7.dll"
  File "..\..\out\ui_main.dist\libssl-1_1.dll"
  SetOutPath "$INSTDIR\log_dir"
  File "..\..\out\ui_main.dist\log_dir\sis_v1.1.2-beta.2.240410_2024-04-10.log"
  SetOutPath "$INSTDIR"
  File "..\..\out\ui_main.dist\msvcp140.dll"
  File "..\..\out\ui_main.dist\msvcp140_1.dll"
  SetOutPath "$INSTDIR\numpy\core"
  File "..\..\out\ui_main.dist\numpy\core\_multiarray_tests.pyd"
  File "..\..\out\ui_main.dist\numpy\core\_multiarray_umath.pyd"
  SetOutPath "$INSTDIR\numpy\fft"
  File "..\..\out\ui_main.dist\numpy\fft\_pocketfft_internal.pyd"
  SetOutPath "$INSTDIR\numpy\linalg"
  File "..\..\out\ui_main.dist\numpy\linalg\_umath_linalg.pyd"
  SetOutPath "$INSTDIR\numpy\random"
  File "..\..\out\ui_main.dist\numpy\random\bit_generator.pyd"
  File "..\..\out\ui_main.dist\numpy\random\mtrand.pyd"
  File "..\..\out\ui_main.dist\numpy\random\_bounded_integers.pyd"
  File "..\..\out\ui_main.dist\numpy\random\_common.pyd"
  File "..\..\out\ui_main.dist\numpy\random\_generator.pyd"
  File "..\..\out\ui_main.dist\numpy\random\_mt19937.pyd"
  File "..\..\out\ui_main.dist\numpy\random\_pcg64.pyd"
  File "..\..\out\ui_main.dist\numpy\random\_philox.pyd"
  File "..\..\out\ui_main.dist\numpy\random\_sfc64.pyd"
  SetOutPath "$INSTDIR\numpy.libs"
  File "..\..\out\ui_main.dist\numpy.libs\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll"
  SetOutPath "$INSTDIR\PIL"
  File "..\..\out\ui_main.dist\PIL\_imaging.pyd"
  File "..\..\out\ui_main.dist\PIL\_imagingmath.pyd"
  SetOutPath "$INSTDIR\psutil"
  File "..\..\out\ui_main.dist\psutil\_psutil_windows.pyd"
  SetOutPath "$INSTDIR"
  File "..\..\out\ui_main.dist\pyexpat.pyd"
  SetOutPath "$INSTDIR\PyQt5\qt-plugins\imageformats"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\imageformats\qgif.dll"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\imageformats\qicns.dll"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\imageformats\qico.dll"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\imageformats\qjpeg.dll"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\imageformats\qsvg.dll"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\imageformats\qtga.dll"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\imageformats\qtiff.dll"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\imageformats\qwbmp.dll"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\imageformats\qwebp.dll"
  SetOutPath "$INSTDIR\PyQt5\qt-plugins\platforms"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\platforms\qwindows.dll"
  SetOutPath "$INSTDIR\PyQt5\qt-plugins\styles"
  File "..\..\out\ui_main.dist\PyQt5\qt-plugins\styles\qwindowsvistastyle.dll"
  SetOutPath "$INSTDIR\PyQt5"
  File "..\..\out\ui_main.dist\PyQt5\QtChart.pyd"
  File "..\..\out\ui_main.dist\PyQt5\QtCore.pyd"
  File "..\..\out\ui_main.dist\PyQt5\QtGui.pyd"
  File "..\..\out\ui_main.dist\PyQt5\QtWidgets.pyd"
  File "..\..\out\ui_main.dist\PyQt5\sip.pyd"
  SetOutPath "$INSTDIR"
  File "..\..\out\ui_main.dist\python3.dll"
  File "..\..\out\ui_main.dist\python39.dll"
  File "..\..\out\ui_main.dist\qt5charts.dll"
  File "..\..\out\ui_main.dist\qt5core.dll"
  File "..\..\out\ui_main.dist\qt5gui.dll"
  File "..\..\out\ui_main.dist\qt5svg.dll"
  File "..\..\out\ui_main.dist\qt5widgets.dll"
  File "..\..\out\ui_main.dist\select.pyd"
  SetOutPath "$INSTDIR\selenium\webdriver\common\windows"
  File "..\..\out\ui_main.dist\selenium\webdriver\common\windows\selenium-manager.exe"
  SetOutPath "$INSTDIR"
  File "..\..\out\ui_main.dist\SISSoftwareLicence.txt"
  File "..\..\out\ui_main.dist\ui_main.exe"
  File "..\..\out\ui_main.dist\unicodedata.pyd"
  File "..\..\out\ui_main.dist\vcruntime140.dll"
  File "..\..\out\ui_main.dist\vcruntime140_1.dll"
  SetOutPath "$INSTDIR\zstandard"
  File "..\..\out\ui_main.dist\zstandard\backend_c.pyd"
  SetOutPath "$INSTDIR\_argon2_cffi_bindings"
  File "..\..\out\ui_main.dist\_argon2_cffi_bindings\_ffi.pyd"
  SetOutPath "$INSTDIR"
  File "..\..\out\ui_main.dist\_asyncio.pyd"
  File "..\..\out\ui_main.dist\_bz2.pyd"
  File "..\..\out\ui_main.dist\_cffi_backend.pyd"
  File "..\..\out\ui_main.dist\_ctypes.pyd"
  File "..\..\out\ui_main.dist\_decimal.pyd"
  File "..\..\out\ui_main.dist\_elementtree.pyd"
  File "..\..\out\ui_main.dist\_hashlib.pyd"
  File "..\..\out\ui_main.dist\_lzma.pyd"
  File "..\..\out\ui_main.dist\_overlapped.pyd"
  File "..\..\out\ui_main.dist\_queue.pyd"
  File "..\..\out\ui_main.dist\_socket.pyd"
  File "..\..\out\ui_main.dist\_ssl.pyd"
  File "..\..\out\ui_main.dist\_uuid.pyd"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\spider_image_system.lnk" "$INSTDIR\selenium\webdriver\common\windows\selenium-manager.exe"
  CreateShortCut "$DESKTOP\spider_image_system.lnk" "$INSTDIR\selenium\webdriver\common\windows\selenium-manager.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\selenium\webdriver\common\windows\selenium-manager.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\selenium\webdriver\common\windows\selenium-manager.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} ""
!insertmacro MUI_FUNCTION_DESCRIPTION_END


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\_uuid.pyd"
  Delete "$INSTDIR\_ssl.pyd"
  Delete "$INSTDIR\_socket.pyd"
  Delete "$INSTDIR\_queue.pyd"
  Delete "$INSTDIR\_overlapped.pyd"
  Delete "$INSTDIR\_lzma.pyd"
  Delete "$INSTDIR\_hashlib.pyd"
  Delete "$INSTDIR\_elementtree.pyd"
  Delete "$INSTDIR\_decimal.pyd"
  Delete "$INSTDIR\_ctypes.pyd"
  Delete "$INSTDIR\_cffi_backend.pyd"
  Delete "$INSTDIR\_bz2.pyd"
  Delete "$INSTDIR\_asyncio.pyd"
  Delete "$INSTDIR\_argon2_cffi_bindings\_ffi.pyd"
  Delete "$INSTDIR\zstandard\backend_c.pyd"
  Delete "$INSTDIR\vcruntime140_1.dll"
  Delete "$INSTDIR\vcruntime140.dll"
  Delete "$INSTDIR\unicodedata.pyd"
  Delete "$INSTDIR\ui_main.exe"
  Delete "$INSTDIR\SISSoftwareLicence.txt"
  Delete "$INSTDIR\selenium\webdriver\common\windows\selenium-manager.exe"
  Delete "$INSTDIR\select.pyd"
  Delete "$INSTDIR\qt5widgets.dll"
  Delete "$INSTDIR\qt5svg.dll"
  Delete "$INSTDIR\qt5gui.dll"
  Delete "$INSTDIR\qt5core.dll"
  Delete "$INSTDIR\qt5charts.dll"
  Delete "$INSTDIR\python39.dll"
  Delete "$INSTDIR\python3.dll"
  Delete "$INSTDIR\PyQt5\sip.pyd"
  Delete "$INSTDIR\PyQt5\QtWidgets.pyd"
  Delete "$INSTDIR\PyQt5\QtGui.pyd"
  Delete "$INSTDIR\PyQt5\QtCore.pyd"
  Delete "$INSTDIR\PyQt5\QtChart.pyd"
  Delete "$INSTDIR\PyQt5\qt-plugins\styles\qwindowsvistastyle.dll"
  Delete "$INSTDIR\PyQt5\qt-plugins\platforms\qwindows.dll"
  Delete "$INSTDIR\PyQt5\qt-plugins\imageformats\qwebp.dll"
  Delete "$INSTDIR\PyQt5\qt-plugins\imageformats\qwbmp.dll"
  Delete "$INSTDIR\PyQt5\qt-plugins\imageformats\qtiff.dll"
  Delete "$INSTDIR\PyQt5\qt-plugins\imageformats\qtga.dll"
  Delete "$INSTDIR\PyQt5\qt-plugins\imageformats\qsvg.dll"
  Delete "$INSTDIR\PyQt5\qt-plugins\imageformats\qjpeg.dll"
  Delete "$INSTDIR\PyQt5\qt-plugins\imageformats\qico.dll"
  Delete "$INSTDIR\PyQt5\qt-plugins\imageformats\qicns.dll"
  Delete "$INSTDIR\PyQt5\qt-plugins\imageformats\qgif.dll"
  Delete "$INSTDIR\pyexpat.pyd"
  Delete "$INSTDIR\psutil\_psutil_windows.pyd"
  Delete "$INSTDIR\PIL\_imagingmath.pyd"
  Delete "$INSTDIR\PIL\_imaging.pyd"
  Delete "$INSTDIR\numpy.libs\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll"
  Delete "$INSTDIR\numpy\random\_sfc64.pyd"
  Delete "$INSTDIR\numpy\random\_philox.pyd"
  Delete "$INSTDIR\numpy\random\_pcg64.pyd"
  Delete "$INSTDIR\numpy\random\_mt19937.pyd"
  Delete "$INSTDIR\numpy\random\_generator.pyd"
  Delete "$INSTDIR\numpy\random\_common.pyd"
  Delete "$INSTDIR\numpy\random\_bounded_integers.pyd"
  Delete "$INSTDIR\numpy\random\mtrand.pyd"
  Delete "$INSTDIR\numpy\random\bit_generator.pyd"
  Delete "$INSTDIR\numpy\linalg\_umath_linalg.pyd"
  Delete "$INSTDIR\numpy\fft\_pocketfft_internal.pyd"
  Delete "$INSTDIR\numpy\core\_multiarray_umath.pyd"
  Delete "$INSTDIR\numpy\core\_multiarray_tests.pyd"
  Delete "$INSTDIR\msvcp140_1.dll"
  Delete "$INSTDIR\msvcp140.dll"
  Delete "$INSTDIR\log_dir\sis_v1.1.2-beta.2.240410_2024-04-10.log"
  Delete "$INSTDIR\libssl-1_1.dll"
  Delete "$INSTDIR\libffi-7.dll"
  Delete "$INSTDIR\libcrypto-1_1.dll"
  Delete "$INSTDIR\data\href_url\klee_result_url.txt"
  Delete "$INSTDIR\cv2\cv2.pyd"
  Delete "$INSTDIR\Crypto\Util\_strxor.pyd"
  Delete "$INSTDIR\Crypto\Util\_cpuid_c.pyd"
  Delete "$INSTDIR\Crypto\Protocol\_scrypt.pyd"
  Delete "$INSTDIR\Crypto\Hash\_SHA256.pyd"
  Delete "$INSTDIR\Crypto\Hash\_SHA1.pyd"
  Delete "$INSTDIR\Crypto\Hash\_poly1305.pyd"
  Delete "$INSTDIR\Crypto\Hash\_ghash_portable.pyd"
  Delete "$INSTDIR\Crypto\Hash\_ghash_clmul.pyd"
  Delete "$INSTDIR\Crypto\Hash\_BLAKE2s.pyd"
  Delete "$INSTDIR\Crypto\Cipher\_Salsa20.pyd"
  Delete "$INSTDIR\Crypto\Cipher\_raw_ofb.pyd"
  Delete "$INSTDIR\Crypto\Cipher\_raw_ocb.pyd"
  Delete "$INSTDIR\Crypto\Cipher\_raw_ecb.pyd"
  Delete "$INSTDIR\Crypto\Cipher\_raw_ctr.pyd"
  Delete "$INSTDIR\Crypto\Cipher\_raw_cfb.pyd"
  Delete "$INSTDIR\Crypto\Cipher\_raw_cbc.pyd"
  Delete "$INSTDIR\Crypto\Cipher\_raw_aesni.pyd"
  Delete "$INSTDIR\Crypto\Cipher\_raw_aes.pyd"
  Delete "$INSTDIR\Crypto\Cipher\_chacha20.pyd"
  Delete "$INSTDIR\config\user-agent.txt"
  Delete "$INSTDIR\config\config.ini"
  Delete "$INSTDIR\charset_normalizer\md__mypyc.pyd"
  Delete "$INSTDIR\charset_normalizer\md.pyd"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\Website.lnk"
  Delete "$DESKTOP\spider_image_system.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\spider_image_system.lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR\zstandard"
  RMDir "$INSTDIR\selenium\webdriver\common\windows"
  RMDir "$INSTDIR\PyQt5\qt-plugins\styles"
  RMDir "$INSTDIR\PyQt5\qt-plugins\platforms"
  RMDir "$INSTDIR\PyQt5\qt-plugins\imageformats"
  RMDir "$INSTDIR\PyQt5"
  RMDir "$INSTDIR\psutil"
  RMDir "$INSTDIR\PIL"
  RMDir "$INSTDIR\numpy\random"
  RMDir "$INSTDIR\numpy\linalg"
  RMDir "$INSTDIR\numpy\fft"
  RMDir "$INSTDIR\numpy\core"
  RMDir "$INSTDIR\numpy.libs"
  RMDir "$INSTDIR\log_dir"
  RMDir "$INSTDIR\data\href_url"
  RMDir "$INSTDIR\cv2"
  RMDir "$INSTDIR\Crypto\Util"
  RMDir "$INSTDIR\Crypto\Protocol"
  RMDir "$INSTDIR\Crypto\Hash"
  RMDir "$INSTDIR\Crypto\Cipher"
  RMDir "$INSTDIR\config"
  RMDir "$INSTDIR\charset_normalizer"
  RMDir "$INSTDIR\_argon2_cffi_bindings"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd